try:
    print("Hallo")
    raise Exception
finally:
    print("finally")